export class Student {
id : String =""
admissionno: string = ""
name: string = ""
admissionclass: string = ""
studentdob: string = ""
gender: string = ""
fathername: string = ""
fatherage: string = ""
fatherqualification: string = ""
fatherdob: string = ""
fatherprofession: string = ""
mothername: string = ""
motherage: string = ""
motherqualification: string = ""
motherdob: string = ""
motherprofession: string = ""
address: string = ""
phoneno: string = ""
cellno: string = ""
emailaddress: string = ""

}
