export default [
    {
      id:"1",
    admissionno: '5123',
    name:   'Rahul Mittal',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdas',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"2",
    admissionno: '5554',
    name:   'Harsimranjeet Singh',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"3",
    admissionno: '5554',
    name:   'Sailesh Khushwa',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"4",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"5",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"6",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"7",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"8",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"9",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"10",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"11",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"12",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"13",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"14",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"15",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"16",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"17",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"18",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"19",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"20",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"21",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"22",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"23",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"24",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"25",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"26",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"27",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"28",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"29",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"30",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  },{
    id:"31",
    admissionno: '5554',
    name:   'Rahul vervwev',
    admissionclass:   '6th A',
    studentdob:   ' 13-05-1990',
    gender:   'M',
    fathername:   'asdsa das da',
    fatherage:   ' 55',
    fatherqualification:   '12th',
    fatherdob:   '13-05-1990',
    fatherprofession:   ' A',
    mothername:   'AAS',
    motherage:   ' ASD',
    motherqualification:   'AS',
    motherdob:   '13-05-1990',
    motherprofession:   'ASD',
    address:   'SDA',
    phoneno:   'ASD',
    cellno:   'SDA',
    emailaddress:   'SDAS'
    
  }
]